apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-production
  labels:
    type: local
spec:
  storageClassName: mongo-pv-production
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /ALL-Data/Production/rt-students.xyz/MongoDB-3.6.3v
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-production
spec:
  storageClassName: mongo-pv-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-production
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-production
spec:
  selector:
    matchLabels:
      app: mongo-production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-production
    spec:
      nodeName: kubernetes-db 
      containers:
      - image: mongo:3.6.3
        name: mongo-pro
        ports:
        - containerPort: 27017
          name: mongo-pro
        volumeMounts:
        - name: mongo-pv-production
          mountPath: /data/db
      volumes:
      - name: mongo-pv-production
        persistentVolumeClaim:
          claimName: mongo-pvc-production
